### ISSUE TITLE
Version attribute not using wrapper cookbooks override.

### ISSUE THREAD

**Issue by daveallen** [ernestas-poskus/chef-proxysql#15]
The proxysql cookbook is setting this in the repository.rb attributes file:
default['proxysql']['package_version'] = "#{node['proxysql']['version']}-1.1.#{lsb_release}"

So when any other cookbooks set the ['proxysql']['version'] attribute the ['proxysql']['package_version'] attribute has already set with what is in the proxysql cookbook ignoring what the wrapper cookbook set.

**Comment by ernestas-poskus** [comment]
@daveallen hm, I see, I think we can get around this problem deriving `package_version` in proxysql_service.rb check this out https://github.com/ernestas-poskus/chef-proxysql/pull/23

**Comment by daveallen** [comment]
Yes that looks like it will work.

**Comment by ernestas-poskus** [comment]
@daveallen hey, I have released new version https://github.com/ernestas-poskus/chef-proxysql/releases/tag/v2.0.0 with new `package_release` attribute so now you should be able to control version. If this change solves your problem please close issue.

**Comment by daveallen** [comment]
Yes this solved that problem.  I have discovered another one.  lol  Will create a new issue.
