### ISSUE TITLE
Open file default limit it limiting proxysq.

### ISSUE THREAD

**Issue by daveallen** [ernestas-poskus/chef-proxysql#33]
I ran into this problem with having 1500 connections on one of my systems.  Proxysql was throwing errors and bringing the load to a halt.

The proxysql user default open files limit is 1024 and that restricts the number of db connections proxysql can handle.  The guys at Proxysql suggested this in the systemd unit file:
LimitNOFILE=102400

Is there a way we can add extra options to the unit file that is being created by the proxysql cookbook so that we can change this value as needed?

Thanks!

**Comment by ernestas-poskus** [comment]
I think it should be possible to pass `LimitNoFILE` option to poise service https://github.com/poise/poise-service#service-options

**Comment by daveallen** [comment]
I tried use an attribute and a service provider:
override['poise-service']['options']['LimitNOFILE'] = '102400'
and
poise_service_options 'proxysql' do
  LimitNOFILE 102400
end

So I just don't understand what they are saying. I will look deeper, but if you could see if it comes easier to you that would be great!

**Comment by ernestas-poskus** [comment]
Have tested poise options and it does not work for me either.. I think I will drop support for sysvinit and will create custom systemd template.

**Comment by daveallen** [comment]
Bummer, that capability should be in the poise cookbook.  I guess it sort of is with the ability to create your own template.  But something like that should be basic.

**Comment by ernestas-poskus** [comment]
For reference, missing configuration 

LimitNOFILE=102400
LimitCORE=1073741824

**Comment by ernestas-poskus** [comment]
cc @daveallen please check if the problem persists I have released 3.0.0 version

**Comment by daveallen** [comment]
Everything looks good!
Thanks!
